version: "3"
networks:
  webserver:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
 
services:
  web:
    build: ./nginx/
    image: service-web
    container_name: service-web
    hostname: service-web
    networks:
      webserver:
        ipv4_address: 172.16.238.10
    ports:
      - 80:80
    volumes:
      - $PWD/timezone/Shanghai:/etc/localtime:ro
      - $SITE_DIR:/www/sites
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/log:/var/log/nginx
    links: 
      - php
    dns:
      - 223.5.5.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php:
    build: ./php/
    image: service-php
    container_name: service-php
    hostname: service-php
    networks:
      webserver:
        ipv4_address: 172.16.238.11
    volumes:
      - $SITE_DIR:/www/sites
      - $PWD/timezone/Shanghai:/etc/localtime:ro
    extra_hosts:
      - "used-dev.com:172.16.238.10"
      - "clake-dev.com:172.16.238.10"
      - "host.docker.internal:host-gateway"
    dns:
      - 223.5.5.5
  redis:
    # build: ./redis/
    image: redis:6-alpine
    container_name: service-redis
    hostname: service-redis
    volumes:
      - $PWD/timezone/Shanghai:/etc/localtime:ro
      - $PWD/redis/data:/data
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379
    networks:
      webserver:
        ipv4_address: 172.16.238.12
    dns:
      - 223.5.5.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    # build: ./mysql/
    image: mysql:5.7
    container_name: service-mysql
    hostname: service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
      - $PWD/mysql/etc:/etc/mysql/conf.d
      - $PWD/timezone/Shanghai:/etc/localtime:ro
    dns:
      - 223.5.5.5
    networks:
      webserver:
        ipv4_address: 172.16.238.13
  mongo:
    image: mongo
    restart: always
    container_name: service-mongo
    hostname: service-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
    ports:
      - 27018:27017
    volumes:
      - $PWD/mongo/data:/data/db
      - $PWD/timezone/Shanghai:/etc/localtime:ro
    dns:
      - 223.5.5.5
    networks:
      webserver:
        ipv4_address: 172.16.238.14
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123123
      ME_CONFIG_MONGODB_URL: mongodb://root:123123@service-mongo:27017/
    dns:
      - 223.5.5.5
    networks:
      webserver:
        ipv4_address: 172.16.238.15
